# Generated by Django 6.0 on 2025-12-13 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_category_rename_bio_tailorprofile_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سفارش')),
                ('description', models.TextField(verbose_name='توضیحات سفارش')),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='order_designs/', verbose_name='عکس طرح')),
                ('size', models.CharField(choices=[('xs', 'اکس\u200cاسمال'), ('s', 'اسمال'), ('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'اکس\u200cلارج'), ('2xl', '۲ اکس\u200cلارج'), ('3xl', '۳ اکس\u200cلارج'), ('custom', 'سایز سفارشی')], max_length=10, verbose_name='سایز')),
                ('custom_size', models.TextField(blank=True, null=True, verbose_name='اندازه\u200cهای دقیق (سانتی\u200cمتر)')),
                ('fabric_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس پارچه')),
                ('color_preference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رنگ\u200cبندی')),
                ('max_budget', models.IntegerField(verbose_name='حداکثر بودجه (تومان)')),
                ('deadline_days', models.IntegerField(verbose_name='حداکثر زمان تحویل (روز)')),
                ('status', models.CharField(choices=[('pending', 'منتظر خیاط'), ('offers_received', 'دریافت پیشنهادات'), ('in_progress', 'در دست ساخت'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش خیاطی',
                'verbose_name_plural': 'سفارشات خیاطی',
                'ordering': ['-created_at'],
            },
        ),
    ]
