# Generated by Django 6.0 on 2025-12-13 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sewingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.IntegerField(verbose_name='قیمت پیشنهادی (تومان)')),
                ('delivery_days', models.IntegerField(verbose_name='زمان تحویل (روز)')),
                ('message', models.TextField(verbose_name='پیام به مشتری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.sewingorder')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشنهاد خیاط',
                'verbose_name_plural': 'پیشنهادات خیاطان',
                'ordering': ['proposed_price'],
                'unique_together': {('tailor', 'order')},
            },
        ),
    ]
